# Generated by Django 6.0.4 on 2026-05-14 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyMaster',
            fields=[
                ('allergy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('allergy_name_kr', models.CharField(max_length=100)),
                ('allergy_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'AllergyMaster',
            },
        ),
        migrations.CreateModel(
            name='SkinConcernMaster',
            fields=[
                ('concern_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concern_name_kr', models.CharField(max_length=100)),
                ('concern_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SkinConcernMaster',
            },
        ),
        migrations.CreateModel(
            name='SkinTypeMaster',
            fields=[
                ('skin_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skin_type_code', models.CharField(max_length=10, unique=True)),
                ('skin_type_name_kr', models.CharField(max_length=100)),
                ('skin_type_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SkinTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_type', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=255)),
                ('save_table', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_master', models.CharField(blank=True, max_length=100, null=True)),
                ('score_field', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'SurveyQuestion',
            },
        ),
        migrations.CreateModel(
            name='TextureMaster',
            fields=[
                ('texture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('texture_name_kr', models.CharField(max_length=100)),
                ('texture_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TextureMaster',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('option_id', models.IntegerField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=100)),
                ('score_value', models.IntegerField()),
                ('score_field', models.CharField(max_length=50)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='users.surveyquestion')),
            ],
            options={
                'db_table': 'SurveyOption',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('answers_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'SurveyResponse',
            },
        ),
        migrations.CreateModel(
            name='UserSkinProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensitivity_level', models.IntegerField(blank=True, null=True)),
                ('acne_prone_flag', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('preferred_texture', models.ForeignKey(blank=True, db_column='preferred_texture_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.texturemaster')),
                ('skin_type', models.ForeignKey(blank=True, db_column='skin_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.skintypemaster')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserSkinProfile',
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(db_column='allergy_id', on_delete=django.db.models.deletion.CASCADE, to='users.allergymaster')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserAllergy',
                'unique_together': {('user', 'allergy')},
            },
        ),
        migrations.CreateModel(
            name='UserSkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.ForeignKey(db_column='concern_id', on_delete=django.db.models.deletion.CASCADE, to='users.skinconcernmaster')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserSkinConcern',
                'unique_together': {('user', 'concern')},
            },
        ),
    ]
