# Generated by Django 6.0.4 on 2026-06-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('related_product_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'PointHistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
