# Generated by Django 6.0.4 on 2026-06-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0005_user_points_pointhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredientCandidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_count', models.IntegerField(default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='products.ingredient')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'ProductIngredientCandidate',
                'unique_together': {('product', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='ProductScanContribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('detected_count', models.IntegerField(default=0)),
                ('reward_points', models.IntegerField(default=0)),
                ('is_first', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ProductScanContribution',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
