# Generated by Django 6.0.4 on 2026-05-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('recommendation', '0001_initial'),
        ('users', '0002_user_kakao_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoutine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='나의 루틴', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserRoutine',
            },
        ),
        migrations.CreateModel(
            name='UserRoutineStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name_custom', models.CharField(blank=True, max_length=200, null=True)),
                ('step_order', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('routine', models.ForeignKey(db_column='routine_id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recommendation.userroutine')),
            ],
            options={
                'db_table': 'UserRoutineStep',
                'ordering': ['step_order'],
            },
        ),
    ]
