# Generated by Django 6.0.4 on 2026-05-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='review.review')),
            ],
            options={
                'db_table': 'ReviewImage',
                'ordering': ['order', 'image_id'],
            },
        ),
    ]
