# Generated by Django 6.0.4 on 2026-05-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('review', '0002_reviewimage'),
        ('users', '0002_user_kakao_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ProductView',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
