# Generated by Django 6.0.4 on 2026-05-14 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'AnalysisResult',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'ChatSession',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_ingredient', models.ForeignKey(blank=True, db_column='related_ingredient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ingredient')),
                ('related_product', models.ForeignKey(blank=True, db_column='related_product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.chatsession')),
            ],
            options={
                'db_table': 'ChatMessage',
            },
        ),
        migrations.CreateModel(
            name='OCR_AnalysisDetail',
            fields=[
                ('analysis_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('detected_text', models.TextField(blank=True, null=True)),
                ('risk_contribution', models.FloatField(blank=True, null=True)),
                ('caution_reason', models.TextField(blank=True, null=True)),
                ('match_status', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis', models.ForeignKey(db_column='analysis_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisresult')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='products.ingredient')),
            ],
            options={
                'db_table': 'OCR_AnalysisDetail',
            },
        ),
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('ocr_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('image_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'OCRImage',
            },
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ocr_image',
            field=models.ForeignKey(blank=True, db_column='ocr_image_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.ocrimage'),
        ),
        migrations.CreateModel(
            name='OCRRawText',
            fields=[
                ('raw_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('ocr_engine', models.CharField(blank=True, max_length=100, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_image', models.ForeignKey(db_column='ocr_image_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.ocrimage')),
            ],
            options={
                'db_table': 'OCRRawText',
            },
        ),
    ]
