# Generated by Django 6.0.4 on 2026-05-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='cautions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='effects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='usage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
